#!/bin/sh
////////////////////////////////////////////////////////////////////
// Script to call collector
///////////////////////////////////////////////////////////////////
//Setup classpath using compiled bytes in ../out (may need to change) 
L=`dirname $0`/../out
cp=`echo $L/*.jar|sed 's/ /:/g'`
exec scala -classpath $cp $0 $@
!#
//Imports
import org.treasuremaps.application.TreasureCollector
//Actual script 
val collector = new TreasureCollector
//TODO... any method other than hello does not work, this is scala newbishness, needs to call something other than hello...
collector.hello
