CONNECT 'jdbc:derby:treasuremaps;create=true';
DROP TABLE STREETS;
CREATE TABLE STREETS (ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), STREET_NAME VARCHAR(20) NOT NULL, STREET_TYPE VARCHAR(10) NOT NULL, STREET_FULL VARCHAR(255) NOT NULL);
DISCONNECT;
EXIT;